### ISSUE TITLE
Error in CurrencyConvertor.java file

### ISSUE THREAD

**Issue by arsalan-rashid** [tobiasbueschel/simple-java-programs#1]
Error:(45, 12) java: invalid method declaration; return type required 

on "public Exercise2_CurrencyConverter()"

There is no Exercise2_CurrencyConverter java file. Should it be created to get ride of this error?

**Comment by tobiasbueschel** [comment]
Hi @meetsani,

Thanks for raising the issue. Yes, you are right! 

I have fixed it in this PR: https://github.com/tobiasbueschel/simple-java-programs/commit/2606a384fa879aa3615c75870260f40e640d30d8

Let me know if it works & keep in mind that you might need to download any dependency jars and add them to your classpath before running `CurrencyConverter`. Also, you need to make sure that the `rates.txt` is at the correct path.

Cheers
